url: "https://did.app" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.
abstract: "Passwordless authentication for your websites and apps."

collections:
  articles:
    output: true
    permalink: /:collection/:title

include:
  - _headers
  - .well-known/openid-configuration

exclude:
  - "package-lock.json"
  - "package.json"
  - "postcss.config.js"
  - "purgecss.config.js"
  - "tailwind.config.js"

plugins:
  - jekyll-postcss
  - jekyll-purgecss
